# Generated by `zs workspace create` / `zs cloud`. Safe to edit & commit.
variable "project_id" { type = string }
variable "project_number" { type = string }
variable "github_owner" { type = string }
variable "github_repo" { type = string }
variable "github_owner_id" {
  type    = string
  default = ""
}
variable "deployer_sa_email" { type = string }
variable "pool_id" {
  type    = string
  default = "github-actions"
}

resource "google_iam_workload_identity_pool" "pool" {
  project                   = var.project_id
  workload_identity_pool_id = var.pool_id
  display_name              = "GitHub Actions"
}

resource "google_iam_workload_identity_pool_provider" "github" {
  project                            = var.project_id
  workload_identity_pool_id          = google_iam_workload_identity_pool.pool.workload_identity_pool_id
  workload_identity_pool_provider_id = "github"
  display_name                       = "GitHub OIDC"

  attribute_mapping = {
    "google.subject"       = "assertion.sub"
    "attribute.repository" = "assertion.repository"
    "attribute.actor"      = "assertion.actor"
    "attribute.ref"        = "assertion.ref"
  }

  # Restrict the pool to this repository (and owner, when the numeric id is supplied).
  attribute_condition = var.github_owner_id != "" ? "assertion.repository_owner_id == \"${var.github_owner_id}\" && attribute.repository == \"${var.github_owner}/${var.github_repo}\"" : "attribute.repository == \"${var.github_owner}/${var.github_repo}\""

  oidc {
    issuer_uri = "https://token.actions.githubusercontent.com"
  }
}

# Let the GitHub repo impersonate the deployer SA (keyless).
resource "google_service_account_iam_member" "wif" {
  service_account_id = "projects/${var.project_id}/serviceAccounts/${var.deployer_sa_email}"
  role               = "roles/iam.workloadIdentityUser"
  member             = "principalSet://iam.googleapis.com/projects/${var.project_number}/locations/global/workloadIdentityPools/${google_iam_workload_identity_pool.pool.workload_identity_pool_id}/attribute.repository/${var.github_owner}/${var.github_repo}"
}

output "provider_name" {
  value = "projects/${var.project_number}/locations/global/workloadIdentityPools/${google_iam_workload_identity_pool.pool.workload_identity_pool_id}/providers/${google_iam_workload_identity_pool_provider.github.workload_identity_pool_provider_id}"
}
