/**
 * Generates `apps/music-collection/src/environments/version.ts`: the build
 * suffix that the environments append to their own base version
 * (`1.0.0` → `1.0.0-build.42+abc1234`), so every deployed build gets its own
 * version:
 *
 *   build.<GITHUB_RUN_NUMBER>+<commit>   (CI)
 *   local+<commit>[.dirty]               (local)
 *
 * The file is generated (gitignored); the `version` Nx target runs this
 * before build, serve and test.
 */

import { execSync } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const TARGET = join(
	ROOT,
	'apps/music-collection/src/environments/version.ts'
);

function git(command) {
	try {
		return execSync(`git ${command}`, { cwd: ROOT, encoding: 'utf8' }).trim();
	} catch {
		return '';
	}
}

const commit =
	process.env.GITHUB_SHA?.slice(0, 7) || git('rev-parse --short HEAD') || 'unknown';
const runNumber = process.env.GITHUB_RUN_NUMBER;
const dirty = !runNumber && git('status --porcelain') !== '';

const build = runNumber
	? `build.${runNumber}+${commit}`
	: `local+${commit}${dirty ? '.dirty' : ''}`;

const info = {
	build,
	commit,
	buildTime: new Date().toISOString(),
};

const source = `// Generated by tools/version/generate-version.mjs — do not edit.
export const VERSION = ${JSON.stringify(info, null, '\t')} as const;
`;

// Only rewrite when the build changed, so the timestamp alone does not
// invalidate the build cache on every local run.
const previous = await readFile(TARGET, 'utf8').catch(() => '');
if (!previous.includes(`"build": ${JSON.stringify(build)}`)) {
	await writeFile(TARGET, source);
}

console.log(`build: ${build}`);
