# Generated by `zs workspace create` / `zs cloud`. Safe to edit & commit.
variable "project_id" { type = string }
variable "deployer_roles" {
  type = list(string)
  default = [
    "roles/firebase.admin",
    "roles/run.admin",
    "roles/cloudfunctions.developer",
    "roles/secretmanager.secretAccessor",
    "roles/iam.serviceAccountUser",
  ]
}

# Keyless deploy identity impersonated by CI via Workload Identity Federation.
resource "google_service_account" "deployer" {
  project      = var.project_id
  account_id   = "ci-deployer"
  display_name = "CI deployer (keyless via WIF)"
}

# Additive (non-authoritative) role grants — never _binding/_policy (would clobber).
resource "google_project_iam_member" "deployer" {
  for_each = toset(var.deployer_roles)
  project  = var.project_id
  role     = each.value
  member   = "serviceAccount:${google_service_account.deployer.email}"
}

output "deployer_email" {
  value = google_service_account.deployer.email
}
