# Generated by `zs workspace create` / `zs cloud`, adapted for music-collection.
# Firebase resources require the google-beta provider.
terraform {
  required_providers {
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "~> 6.0"
    }
  }
}

variable "project_id" { type = string }
variable "hosting_sites" {
  type    = list(string)
  default = []
}
variable "web_app_display_name" {
  type    = string
  default = "music-collection"
}
variable "firestore_location" {
  type        = string
  description = "A Firestore adatbázis helye. Létrehozás után NEM módosítható; a dev a prod helyét követi."
}
variable "app_check_domains" {
  type        = list(string)
  default     = []
  description = "Azok a domainek, ahonnan az App Check reCAPTCHA kulcsa tokent ad (pl. a hosting domainek, devben a localhost). Üresen App Check nem jön létre."
}
variable "firestore_point_in_time_recovery" {
  type        = bool
  default     = false
  description = "Point-in-time recovery (7 napra visszamenő olvasás/visszaállítás) a Firestore adatbázison."
}

resource "google_firebase_project" "this" {
  provider = google-beta
  project  = var.project_id
}

resource "google_firebase_hosting_site" "sites" {
  provider = google-beta
  for_each = toset(var.hosting_sites)
  project  = var.project_id
  site_id  = each.value

  depends_on = [google_firebase_project.this]
}

# Az app ennek a web-SDK konfigurációját kapja (`environment*.ts`).
resource "google_firebase_web_app" "app" {
  provider     = google-beta
  project      = var.project_id
  display_name = var.web_app_display_name

  # ABANDON: a web app törlése minden kliens hitelesítését eltörné — tofu-ból sosem.
  deletion_policy = "ABANDON"

  depends_on = [google_firebase_project.this]
}

resource "google_firestore_database" "default" {
  provider    = google-beta
  project     = var.project_id
  name        = "(default)"
  location_id = var.firestore_location
  type        = "FIRESTORE_NATIVE"

  point_in_time_recovery_enablement = (
    var.firestore_point_in_time_recovery
    ? "POINT_IN_TIME_RECOVERY_ENABLED"
    : "POINT_IN_TIME_RECOVERY_DISABLED"
  )

  # ABANDON: egy destroy a state-ből veszi ki, az adatot nem érinti.
  deletion_policy = "ABANDON"

  depends_on = [google_firebase_project.this]
}

# ── App Check ───────────────────────────────────────────────────────────────
# A callable-ök (apps/functions/src/index.ts: `enforceAppCheck`) App Check
# tokent követelnek, mert a bejelentkezés önmagában nem mondja meg, hogy a hívás
# a mi appunkból jön: egy kimásolt ID tokennel a végpontok scriptből is
# hívhatók lennének, az `identifyRecordFromPhoto` esetében hívásonként egy
# modell-kérés árán.
#
# A kulcs pontozó (SCORE) típusú: a látogató nem kap kirakóst, a reCAPTCHA a
# viselkedésből ad pontot, és a döntést az App Check hozza meg belőle.
resource "google_recaptcha_enterprise_key" "app_check" {
  provider     = google-beta
  count        = length(var.app_check_domains) > 0 ? 1 : 0
  project      = var.project_id
  display_name = "${var.web_app_display_name}-app-check"

  web_settings {
    integration_type = "SCORE"
    allowed_domains  = var.app_check_domains
  }

  depends_on = [google_firebase_project.this]
}

# A web app regisztrálása App Checkbe ezzel a kulccsal. A kliens a kulcs
# nevét (= magát a site key-t) kapja az `environment*.ts`-ben.
resource "google_firebase_app_check_recaptcha_enterprise_config" "app" {
  provider = google-beta
  count    = length(var.app_check_domains) > 0 ? 1 : 0
  project  = var.project_id
  app_id   = google_firebase_web_app.app.app_id
  site_key = google_recaptcha_enterprise_key.app_check[0].name
}

output "app_check_site_key" {
  value       = one(google_recaptcha_enterprise_key.app_check[*].name)
  description = "A reCAPTCHA Enterprise site key — ez megy az environment*.ts `appCheck.recaptchaSiteKey` mezőjébe. Nem titok, a kliensbe kerül."
}

output "web_app_id" {
  value = google_firebase_web_app.app.app_id
}
