/**
 * Generates `apps/music-collection/src/environments/primeui-license.ts`: the
 * PrimeUI license token PrimeNG verifies at startup (`providePrimeNG`).
 *
 * PrimeNG 22 is commercial software (node_modules/primeng/LICENSE.md). A
 * personal project under the revenue, headcount and funding limits qualifies
 * for the free Community License, but it still needs a key: without one the
 * library verifies `unconfigured` and paints a red "Invalid PrimeUI License"
 * banner into the bottom-right corner of every page.
 *
 * The key is tied to the developer who claimed it, and this repository is
 * public, so it never enters it. Sources, in order: the `MC_PRIMEUI_LICENSE`
 * environment variable (that is how CI passes it), then `.primeui-license`,
 * which git does not see:
 *
 *   echo 'PrimeUI-Community-...' > .primeui-license
 *
 * Claim or look up the key at https://primeui.store. Without either source the
 * generated token is empty: everything works, the banner shows.
 *
 * The file is generated (gitignored); the `primeui-license` Nx target runs
 * this before build, serve and test.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const SOURCE = join(ROOT, '.primeui-license');
const TARGET = join(
	ROOT,
	'apps/music-collection/src/environments/primeui-license.ts'
);

const license = (
	process.env.MC_PRIMEUI_LICENSE ||
	(await readFile(SOURCE, 'utf8').catch(() => ''))
).trim();

const source = `// Generated by tools/primeui/generate-license.mjs — do not edit.
export const PRIMEUI_LICENSE = ${JSON.stringify(license)};
`;

// Only rewrite when the key changed, so the build cache survives.
const previous = await readFile(TARGET, 'utf8').catch(() => '');
if (previous !== source) {
	await writeFile(TARGET, source);
}

console.log(
	license
		? 'primeui: license key'
		: 'primeui: no key (no .primeui-license) — the invalid-license banner shows'
);
