# Generated by `zs workspace create` / `zs cloud`, adapted for music-collection.
#
# A dev és a prod gyökér main.tf-je AZONOS; a különbség kizárólag a `<env>.tfvars`-ban él.
#
# A PROJEKTET nem ez a gyökér teremti: a dev-et a bootstrap hozza létre (a state-bucketnek
# előbb kell a projekt), a prod pedig a meglévő `music-collection-4e074`. Itt adatforrásként
# ÁTVESSZÜK, így minden erőforrásnak pontosan egy gazdája van.
data "google_project" "this" {
  project_id = var.project_id
}

resource "google_project_service" "enabled" {
  for_each                   = toset(var.services)
  project                    = data.google_project.this.project_id
  service                    = each.value
  disable_on_destroy         = false
  disable_dependent_services = false
}

locals {
  project_id     = data.google_project.this.project_id
  project_number = data.google_project.this.number
}

module "service_accounts" {
  source     = "../../modules/service-accounts"
  project_id = local.project_id

  # A CI a Hostingot, a Firestore és Storage rules-t és a Firestore indexeket telepíti — a
  # scaffold alapértéke (firebase.admin, run.admin, cloudfunctions, projekt-szintű
  # secretAccessor) ehhez indokolatlanul tág.
  deployer_roles = [
    "roles/firebasehosting.admin",
    "roles/firebaserules.admin",
    "roles/datastore.indexAdmin",
    "roles/firebasestorage.viewer",
    "roles/serviceusage.serviceUsageConsumer",
  ]

  depends_on = [google_project_service.enabled]
}

module "wif" {
  source            = "../../modules/wif"
  project_id        = local.project_id
  project_number    = local.project_number
  github_owner      = var.github_owner
  github_repo       = var.github_repo
  github_owner_id   = var.github_owner_id
  deployer_sa_email = module.service_accounts.deployer_email

  depends_on = [google_project_service.enabled]
}

module "firebase" {
  source             = "../../modules/firebase"
  project_id         = local.project_id
  hosting_sites      = var.hosting_sites
  firestore_location = var.firestore_location

  depends_on = [google_project_service.enabled]
}

module "github_environment" {
  source         = "../../modules/github-environment"
  repository     = var.github_repo
  environment    = var.env
  reviewer_users = var.reviewer_users
  wait_timer     = 0

  deployment_branches = var.deployment_branches

  # A deploy workflow ezekből dolgozik — a címek így nem a workflow-ba égetve élnek.
  environment_variables = {
    GCP_PROJECT      = local.project_id
    WIF_PROVIDER     = module.wif.provider_name
    DEPLOYER_SA      = module.service_accounts.deployer_email
    BUILD_CONFIG     = var.build_configuration
    FIREBASE_HOSTING = var.hosting_target
  }
}
