# Generated by `zs workspace create` / `zs cloud`. Safe to edit & commit.
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "~> 6.0"
    }
    github = {
      source  = "integrations/github"
      version = "~> 6.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = var.region
}

provider "google-beta" {
  project               = var.project_id
  region                = var.region
  user_project_override = true
}

# Authenticates from the token exposed by `gh auth token` (or GITHUB_TOKEN).
provider "github" {
  owner = var.github_owner
}
