# Generated by `zs workspace create` / `zs cloud`, adapted for music-collection.
# A dev és a prod gyökér variables.tf-je AZONOS; az értékek a `<env>.tfvars`-ban vannak.

variable "env" {
  type = string
}

variable "project_id" {
  type = string
}

variable "region" {
  type    = string
  default = "europe-west1"
}

variable "is_production" {
  type    = bool
  default = false
}

variable "github_owner" {
  type    = string
  default = "zs-soft-2"
}

variable "github_repo" {
  type    = string
  default = "music-collection"
}

# Numerikus GitHub szervezet-azonosító: a WIF feltétele így a szervezetre is szűkít.
variable "github_owner_id" {
  type    = string
  default = "79504236"
}

variable "reviewer_users" {
  type    = list(string)
  default = []
}

variable "hosting_sites" {
  type = list(string)
}

variable "hosting_target" {
  type    = string
  default = "app"
}

variable "firestore_location" {
  type = string
}

variable "build_configuration" {
  type = string
}

variable "services" {
  type = list(string)
  default = [
    "cloudresourcemanager.googleapis.com",
    "iam.googleapis.com",
    "iamcredentials.googleapis.com",
    "sts.googleapis.com",
    "serviceusage.googleapis.com",
    "firebase.googleapis.com",
    "firebasehosting.googleapis.com",
    "firestore.googleapis.com",
    "firebaserules.googleapis.com",
    "firebasestorage.googleapis.com",
    "identitytoolkit.googleapis.com",
  ]
}
