# Generated by `zs workspace create` / `zs cloud`. Safe to edit & commit.
terraform {
  backend "gcs" {
    # bucket + prefix are supplied via partial config at init time:
    #   tofu init -backend-config="bucket=music-collection-prod-tfstate" -backend-config="prefix=prod"
  }
}
