# Generated by `zs workspace create` / `zs cloud`, adapted for music-collection.
#
# A dev és a prod gyökér main.tf-je AZONOS; a különbség kizárólag a `<env>.tfvars`-ban él.
#
# A PROJEKTET nem ez a gyökér teremti: a dev-et a bootstrap hozza létre (a state-bucketnek
# előbb kell a projekt), a prod pedig a meglévő `music-collection-4e074`. Itt adatforrásként
# ÁTVESSZÜK, így minden erőforrásnak pontosan egy gazdája van.
data "google_project" "this" {
  project_id = var.project_id
}

resource "google_project_service" "enabled" {
  for_each                   = toset(var.services)
  project                    = data.google_project.this.project_id
  service                    = each.value
  disable_on_destroy         = false
  disable_dependent_services = false
}

locals {
  project_id     = data.google_project.this.project_id
  project_number = data.google_project.this.number
}

# A jogosultság-szinkron function saját futtató service accountja. A Compute
# default SA-t nem használjuk futtatásra: az org policy miatt nincs szerepköre,
# és bármilyen compute-erőforrás felvehetné. Ez csak a Firestore-t éri el, és
# az Eventarc-tól kaphat eseményt. A deployer a projekt-szintű
# serviceAccountUser révén telepíthet a nevében.
resource "google_service_account" "functions_runtime" {
  project      = local.project_id
  account_id   = "functions-runtime"
  display_name = "Cloud Functions runtime (permission sync)"

  depends_on = [google_project_service.enabled]
}

resource "google_project_iam_member" "functions_runtime" {
  for_each = toset([
    "roles/datastore.user",
    "roles/eventarc.eventReceiver",
    "roles/logging.logWriter",
  ])
  project = local.project_id
  role    = each.value
  member  = "serviceAccount:${google_service_account.functions_runtime.email}"
}

# A 2. generációs function képét a Cloud Build a Compute default SA nevében
# építi (új projektekben ez az alapértelmezett build SA). Az org policy miatt
# az Editor-jogot nem kapja meg automatikusan, így a forrást sem tudja letölteni
# ("missing permission on the build service account"). A builder szerepkör
# pontosan a buildhez kellő jogokat adja (forrás olvasása, kép írása, naplózás).
resource "google_project_iam_member" "functions_build" {
  project = local.project_id
  role    = "roles/cloudbuild.builds.builder"
  member  = "serviceAccount:${local.project_number}-compute@developer.gserviceaccount.com"

  depends_on = [google_project_service.enabled]
}

module "service_accounts" {
  source     = "../../modules/service-accounts"
  project_id = local.project_id

  # A CI a Hostingot, a Firestore és Storage rules-t, a Firestore indexeket és a
  # jogosultság-szinkron functiont telepíti — a scaffold alapértéke (firebase.admin,
  # projekt-szintű secretAccessor) ehhez indokolatlanul tág.
  #
  # A 2. generációs function deployjához: kép építése (cloudbuild) és tárolása
  # (artifactregistry), futtatás (run), Firestore-trigger (eventarc), és a futtató
  # service account használata (serviceAccountUser). Az API-kat a fenti
  # `google_project_service.enabled` kapcsolja be, a deployernek csak látnia kell
  # őket (serviceUsageViewer) — bekapcsolnia nem kell.
  #
  # Storage-jogot SZÁNDÉKOSAN nem adunk: a 2. generációs deploy a forrást a
  # Cloud Functions API-tól kapott aláírt URL-re tölti fel, nem IAM-mel. Így a
  # deployer nem fér hozzá a feltöltött borítókhoz sem.
  deployer_roles = [
    "roles/firebasehosting.admin",
    "roles/firebaserules.admin",
    "roles/datastore.indexAdmin",
    "roles/firebasestorage.viewer",
    "roles/serviceusage.serviceUsageConsumer",
    "roles/serviceusage.serviceUsageViewer",
    "roles/cloudfunctions.developer",
    "roles/run.admin",
    "roles/eventarc.developer",
    "roles/cloudbuild.builds.editor",
    "roles/artifactregistry.writer",
    "roles/iam.serviceAccountUser",
  ]

  depends_on = [google_project_service.enabled]
}

module "wif" {
  source            = "../../modules/wif"
  project_id        = local.project_id
  project_number    = local.project_number
  github_owner      = var.github_owner
  github_repo       = var.github_repo
  github_owner_id   = var.github_owner_id
  deployer_sa_email = module.service_accounts.deployer_email

  depends_on = [google_project_service.enabled]
}

module "firebase" {
  source             = "../../modules/firebase"
  project_id         = local.project_id
  hosting_sites      = var.hosting_sites
  firestore_location = var.firestore_location

  depends_on = [google_project_service.enabled]
}

module "github_environment" {
  source         = "../../modules/github-environment"
  repository     = var.github_repo
  environment    = var.env
  reviewer_users = var.reviewer_users
  wait_timer     = 0

  deployment_branches = var.deployment_branches

  # A deploy workflow ezekből dolgozik — a címek így nem a workflow-ba égetve élnek.
  environment_variables = {
    GCP_PROJECT      = local.project_id
    WIF_PROVIDER     = module.wif.provider_name
    DEPLOYER_SA      = module.service_accounts.deployer_email
    BUILD_CONFIG     = var.build_configuration
    FIREBASE_HOSTING = var.hosting_target
  }
}
