# Generated by `zs workspace create` / `zs cloud`. Safe to edit & commit.
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "~> 6.0"
    }
    github = {
      source  = "integrations/github"
      version = "~> 6.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = var.region
}

# A Cloud Billing Budget API-t a hívó „quota project"-je számolja el. A sima
# `google` providert ezért nem bántjuk (a header minden erőforrásra rámenne),
# hanem a budget kap egy sajátot: így a prod apply a prod projekt API-ját
# használja, nem azt, ami a fejlesztő gcloud ADC-jében épp be van állítva.
provider "google" {
  alias                 = "billing"
  project               = var.project_id
  region                = var.region
  billing_project       = var.project_id
  user_project_override = true
}

provider "google-beta" {
  project               = var.project_id
  region                = var.region
  user_project_override = true
}

# Authenticates from the token exposed by `gh auth token` (or GITHUB_TOKEN).
provider "github" {
  owner = var.github_owner
}
