# Generated by `zs workspace create` / `zs cloud`, adapted for music-collection.
# A dev és a prod gyökér variables.tf-je AZONOS; az értékek a `<env>.tfvars`-ban vannak.

variable "env" {
  type = string
}

variable "project_id" {
  type = string
}

variable "region" {
  type    = string
  default = "europe-west1"
}

variable "is_production" {
  type    = bool
  default = false
}

variable "github_owner" {
  type    = string
  default = "zs-soft-2"
}

variable "github_repo" {
  type    = string
  default = "music-collection"
}

# Numerikus GitHub szervezet-azonosító: a WIF feltétele így a szervezetre is szűkít.
variable "github_owner_id" {
  type    = string
  default = "79504236"
}

variable "reviewer_users" {
  type    = list(string)
  default = []
}

variable "hosting_sites" {
  type = list(string)
}

variable "hosting_target" {
  type    = string
  default = "app"
}

variable "firestore_location" {
  type = string
}

variable "firestore_point_in_time_recovery" {
  type    = bool
  default = false
}

variable "build_configuration" {
  type = string
}

variable "services" {
  type = list(string)
  default = [
    "cloudresourcemanager.googleapis.com",
    "iam.googleapis.com",
    "iamcredentials.googleapis.com",
    "sts.googleapis.com",
    "serviceusage.googleapis.com",
    "firebase.googleapis.com",
    "firebasehosting.googleapis.com",
    "firestore.googleapis.com",
    "firebaserules.googleapis.com",
    "firebasestorage.googleapis.com",
    "identitytoolkit.googleapis.com",
    # Cloud Functions (2. generáció) a jogosultság-szinkronhoz: a function Cloud
    # Runon fut, a triggerét az Eventarc kézbesíti, a képét a Cloud Build építi
    # és az Artifact Registry tárolja, a forrás egy Storage-bucketbe kerül.
    "cloudfunctions.googleapis.com",
    "run.googleapis.com",
    "eventarc.googleapis.com",
    "cloudbuild.googleapis.com",
    "artifactregistry.googleapis.com",
    "pubsub.googleapis.com",
    "storage.googleapis.com",
    # A Compute default SA-t (a Cloud Build alapértelmezett build SA-ja) ennek
    # bekapcsolása hozza létre; futó VM-et nem indítunk.
    "compute.googleapis.com",
    # A Discogs token tárolása (DISCOGS_TOKEN secret).
    "secretmanager.googleapis.com",
    # App Check: a callable-ök csak a saját appunkból hívhatók. A reCAPTCHA
    # Enterprise adja a pontot, az App Check a belőle váltott tokent.
    "firebaseappcheck.googleapis.com",
    "recaptchaenterprise.googleapis.com",
    # Vertex AI: a collection badge-eket az Imagen rajzolja meg
    # (generateMusicCollectionBadge).
    "aiplatform.googleapis.com",
  ]
}

variable "app_check_domains" {
  type        = list(string)
  default     = []
  description = "Azok a domainek, ahonnan az App Check reCAPTCHA kulcsa tokent ad. Üresen App Check nem jön létre."
}

variable "deployment_branches" {
  type        = list(string)
  default     = ["main"]
  description = "Az ágak, amelyekről a GitHub environmentbe telepíteni lehet."
}
