export enum GenreEnum {
	Rock = 'Rock',
}

export enum StyleEnum {
	Alternative_Rock = 'Alternative Rock',
	Backened_Doom = 'Blackened Doom',
	Bay_Area_Thrash = 'Bay Area Thrash',
	Death = 'Death',
	Death_Doom = 'Death Doom',
	Deathgrind = 'Deathgrind',
	Glam_Rock = 'Glam Rock',
	Glam_Metal = 'Glam Metal',
	Gothenburg = 'Gothenburg',
	Gothic_Doom = 'Gothic Doom',
	Grindcore = 'Grindcore',
	Groove = 'Groove',
	Hard_Rock = 'Hard rock',
	Heavy = 'Heavy metal',
	Melodic_Death = 'Melodic Death',
	New_Wave_Of_British_Heavy_Metal = 'New Wave Of British Heavy Metal',
	Progressive_Death = 'Progressive Death',
	Progressive_Thrash = 'Progressive Thrash',
	Teachnical_Death = 'Technical Death',
	Teutonic_Thrash = 'Teutonic Thrash',
	Thrash = 'Thrash',
}

export const StyleList: StyleEnum[] = [
	StyleEnum.Alternative_Rock,
	StyleEnum.Backened_Doom,
	StyleEnum.Bay_Area_Thrash,
	StyleEnum.Death,
	StyleEnum.Death_Doom,
	StyleEnum.Deathgrind,
	StyleEnum.Grindcore,
	StyleEnum.Glam_Metal,
	StyleEnum.Glam_Rock,
	StyleEnum.Gothenburg,
	StyleEnum.Gothic_Doom,
	StyleEnum.Groove,
	StyleEnum.Hard_Rock,
	StyleEnum.Heavy,
	StyleEnum.Melodic_Death,
	StyleEnum.New_Wave_Of_British_Heavy_Metal,
	StyleEnum.Progressive_Death,
	StyleEnum.Progressive_Thrash,
	StyleEnum.Teachnical_Death,
	StyleEnum.Teutonic_Thrash,
	StyleEnum.Thrash,
];
