export enum GenreEnum {
	Rock = 'Rock',
}

export enum StyleEnum {
	Alternative_Metal = 'Alternative metal',
	Alternative_Rock = 'Alternative Rock',
	Ambient = 'Ambient',
	Avantgarde_Metal = 'Avantgarde metal',
	Blackened_Doom = 'Blackened Doom',
	Blackened_Thrash = 'Blackened Thrash',
	Bay_Area_Thrash = 'Bay Area Thrash',
	Black = 'Black',
	Blues_Rock = 'Blues Rock',
	Brutal_Death = 'Brutal Death',
	Celtic_Folk_Metal = 'Celtic Folk metal',
	Death = 'Death',
	Death_Doom = 'Death Doom',
	Deathgrind = 'Deathgrind',
	Doom = 'Doom',
	Drone = 'Drone',
	Experimental = 'Experimental',
	First_Wave_Of_Black_Metal = 'First wave of black metal',
	Folk_Metal = 'Folk metal',
	Funk_Rock = 'Funk Rock',
	Glam_Rock = 'Glam Rock',
	Glam_Metal = 'Glam Metal',
	Gothenburg = 'Gothenburg',
	Gothic = 'Gothic',
	Gothic_Doom = 'Gothic Doom',
	Grindcore = 'Grindcore',
	Groove = 'Groove',
	Groove_Thrash = 'Groove Thrash',
	Grunge = 'Grunge',
	Hard_Rock = 'Hard rock',
	Heavy = 'Heavy metal',
	Math_Rock = 'Math Rock',
	Melodic_Death = 'Melodic Death',
	Melodic_Doom = 'Melodic Doom',
	Metalcore = 'Metalcore',
	Noise = 'Noise',
	Noise_Rock = 'Noise Rock',
	New_Wave_Of_British_Heavy_Metal = 'New Wave Of British Heavy Metal',
	Pagan_Thrash = 'Pagan Thrash',
	Power_Metal = 'Power metal',
	Post_Rock = 'Post-Rock',
	Progressive_Metal = 'Progressive metal',
	Progressive_Death = 'Progressive Death',
	Progressive_Thrash = 'Progressive Thrash',
	Psychedelic_Rock = 'Psychedelic Rock',
	Rap_Rock = 'Rap Rock',
	Rock = 'Rock',
	Speed = 'Speed',
	Space_Rock = 'Space Rock',
	Symphonic_Heavy_Metal = 'Symphonic Heavy metal',
	Technical_Death = 'Technical Death',
	Technical_Thrash = 'Technical Thrash',
	Teutonic_Thrash = 'Teutonic Thrash',
	Thrash = 'Thrash',
	US_Power_Metal = 'US Power metal',
}

export const StyleList: StyleEnum[] = [
	StyleEnum.Alternative_Metal,
	StyleEnum.Alternative_Rock,
	StyleEnum.Ambient,
	StyleEnum.Avantgarde_Metal,
	StyleEnum.Blackened_Doom,
	StyleEnum.Blackened_Thrash,
	StyleEnum.Bay_Area_Thrash,
	StyleEnum.Black,
	StyleEnum.Blues_Rock,
	StyleEnum.Brutal_Death,
	StyleEnum.Celtic_Folk_Metal,
	StyleEnum.Death,
	StyleEnum.Death_Doom,
	StyleEnum.Deathgrind,
	StyleEnum.Doom,
	StyleEnum.Drone,
	StyleEnum.Experimental,
	StyleEnum.First_Wave_Of_Black_Metal,
	StyleEnum.Folk_Metal,
	StyleEnum.Funk_Rock,
	StyleEnum.Grindcore,
	StyleEnum.Glam_Metal,
	StyleEnum.Glam_Rock,
	StyleEnum.Gothenburg,
	StyleEnum.Gothic,
	StyleEnum.Gothic_Doom,
	StyleEnum.Groove,
	StyleEnum.Groove_Thrash,
	StyleEnum.Grunge,
	StyleEnum.Hard_Rock,
	StyleEnum.Heavy,
	StyleEnum.Melodic_Death,
	StyleEnum.Melodic_Doom,
	StyleEnum.Math_Rock,
	StyleEnum.Metalcore,
	StyleEnum.Noise,
	StyleEnum.Noise_Rock,
	StyleEnum.New_Wave_Of_British_Heavy_Metal,
	StyleEnum.Pagan_Thrash,
	StyleEnum.Power_Metal,
	StyleEnum.Post_Rock,
	StyleEnum.Progressive_Metal,
	StyleEnum.Progressive_Death,
	StyleEnum.Progressive_Thrash,
	StyleEnum.Psychedelic_Rock,
	StyleEnum.Rap_Rock,
	StyleEnum.Rock,
	StyleEnum.Speed,
	StyleEnum.Space_Rock,
	StyleEnum.Symphonic_Heavy_Metal,
	StyleEnum.Technical_Death,
	StyleEnum.Technical_Thrash,
	StyleEnum.Teutonic_Thrash,
	StyleEnum.Thrash,
	StyleEnum.US_Power_Metal,
];
