export const enum EntityTypeEnum {
	ApplicationConfig = 'ApplicationConfig',
	Artist = 'Artist',
	Album = 'Album',
	Document = 'Document',
	EntityQuantity = 'EntityQuantity',
	Label = 'Label',
	Membership = 'Membership',
	Musician = 'Musician',
	Release = 'Release',
	Track = 'Track',
	CollectionItem = 'Collection Item',
	Contribution = 'Contribution',
	User = 'User',
	WishlistItem = 'Wishlist Item',
}
