export enum GenreEnum {
	Rock = 'Rock',
}

export enum StyleEnum {
	Alternative_Metal = 'Alternative metal',
	Alternative_Rock = 'Alternative Rock',
	Backened_Doom = 'Blackened Doom',
	Bay_Area_Thrash = 'Bay Area Thrash',
	Brutal_Death = 'Brutal Death',
	Death = 'Death',
	Death_Doom = 'Death Doom',
	Deathgrind = 'Deathgrind',
	Doom = 'Doom',
	Folk_Metal = 'Folk metal',
	Glam_Rock = 'Glam Rock',
	Glam_Metal = 'Glam Metal',
	Gothenburg = 'Gothenburg',
	Gothic = 'Gothic',
	Gothic_Doom = 'Gothic Doom',
	Grindcore = 'Grindcore',
	Groove = 'Groove',
	Groove_Thrash = 'Groove Thrash',
	Hard_Rock = 'Hard rock',
	Heavy = 'Heavy metal',
	Melodic_Death = 'Melodic Death',
	Metalcore = 'Metalcore',
	New_Wave_Of_British_Heavy_Metal = 'New Wave Of British Heavy Metal',
	Power_Metal = 'Power metal',
	Progressive_Metal = 'Progressive meta',
	Progressive_Death = 'Progressive Death',
	Progressive_Thrash = 'Progressive Thrash',
	Speed = 'Speed',
	Technical_Death = 'Technical Death',
	Technical_Thrash = 'Technical Thrash',
	Teutonic_Thrash = 'Teutonic Thrash',
	Thrash = 'Thrash',
	US_Power_Metal = 'US Power metal',
}

export const StyleList: StyleEnum[] = [
	StyleEnum.Alternative_Metal,
	StyleEnum.Alternative_Rock,
	StyleEnum.Backened_Doom,
	StyleEnum.Bay_Area_Thrash,
	StyleEnum.Brutal_Death,
	StyleEnum.Death,
	StyleEnum.Death_Doom,
	StyleEnum.Deathgrind,
	StyleEnum.Doom,
	StyleEnum.Folk_Metal,
	StyleEnum.Grindcore,
	StyleEnum.Glam_Metal,
	StyleEnum.Glam_Rock,
	StyleEnum.Gothenburg,
	StyleEnum.Gothic,
	StyleEnum.Gothic_Doom,
	StyleEnum.Groove,
	StyleEnum.Groove_Thrash,
	StyleEnum.Hard_Rock,
	StyleEnum.Heavy,
	StyleEnum.Melodic_Death,
	StyleEnum.Metalcore,
	StyleEnum.New_Wave_Of_British_Heavy_Metal,
	StyleEnum.Power_Metal,
	StyleEnum.Progressive_Metal,
	StyleEnum.Progressive_Death,
	StyleEnum.Progressive_Thrash,
	StyleEnum.Speed,
	StyleEnum.Technical_Death,
	StyleEnum.Technical_Thrash,
	StyleEnum.Teutonic_Thrash,
	StyleEnum.Thrash,
	StyleEnum.US_Power_Metal,
];
