# Generated by `zs workspace create` / `zs cloud`, adapted for music-collection.
#
# A „mindent megelőző" réteg, lokál state-tel: ez teremti azokat a bucketeket, amikbe a
# környezeti gyökerek a state-jüket írják.
#
#   dev  → `music-collection-dev`  ÚJ projekt, ITT jön létre (a bucketnek kell a projekt).
#   prod → `music-collection-4e074` MEGLÉVŐ projekt. A projekt-azonosító nem nevezhető át,
#          ezért a prod csak adatforrásként jelenik meg: a bootstrap nem gazdája, és egy
#          elgépelt destroy sem érheti el.
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
  }
}

provider "google" {
  region = var.region
}

variable "region" {
  type    = string
  default = "europe-west1"
}

variable "org_id" {
  type        = string
  default     = ""
  description = "A szervezet numerikus azonosítója, amely alá a dev projekt kerül (`gcloud organizations list`). Üresen szervezet nélkül jön létre."
}

variable "billing_account" {
  type        = string
  description = "A dev projekt számlázási fiókja (`gcloud billing accounts list`). A state-bucket és a Firebase Storage számlázást igényel."

  validation {
    condition     = can(regex("^[A-F0-9]{6}-[A-F0-9]{6}-[A-F0-9]{6}$", var.billing_account))
    error_message = "A billing_account alakja XXXXXX-XXXXXX-XXXXXX. Lekérdezés: `gcloud billing accounts list`."
  }
}

locals {
  bootstrap_services = [
    "storage.googleapis.com",
    "serviceusage.googleapis.com",
  ]
}

module "dev_project" {
  source          = "../modules/gcp-project"
  project_id      = "music-collection-dev"
  project_name    = "music-collection-dev"
  billing_account = var.billing_account
  org_id          = var.org_id
  services        = local.bootstrap_services
  deletion_policy = "DELETE"
}

data "google_project" "prod" {
  project_id = "music-collection-4e074"
}

locals {
  state_buckets = {
    "dev" = {
      project = module.dev_project.project_id
      bucket  = "music-collection-dev-tfstate"
    }
    "prod" = {
      project = data.google_project.prod.project_id
      bucket  = "music-collection-prod-tfstate"
    }
  }
}

# `force_destroy = false` és verziózás: az állapot elvesztése a topológia elvesztése.
resource "google_storage_bucket" "tfstate" {
  for_each                    = local.state_buckets
  name                        = each.value.bucket
  project                     = each.value.project
  location                    = var.region
  uniform_bucket_level_access = true
  force_destroy               = false

  versioning {
    enabled = true
  }
}

output "state_buckets" {
  value = { for k, b in google_storage_bucket.tfstate : k => b.name }
}
