# Generated by `zs workspace create` / `zs cloud`, adapted for music-collection.
#
# A „mindent megelőző" réteg, lokál state-tel: ez teremti azokat a bucketeket, amikbe a
# környezeti gyökerek a state-jüket írják.
#
#   dev  → `music-collection-16676` MEGLÉVŐ projekt.
#   prod → `music-collection-4e074` MEGLÉVŐ projekt.
# A projekt-azonosító nem nevezhető át, ezért mindkettő csak adatforrásként jelenik meg: a
# bootstrap nem gazdájuk, és egy elgépelt destroy sem érheti el őket.
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
  }
}

provider "google" {
  region = var.region
}

variable "region" {
  type    = string
  default = "europe-west1"
}

data "google_project" "dev" {
  project_id = "music-collection-16676"
}

data "google_project" "prod" {
  project_id = "music-collection-4e074"
}

locals {
  state_buckets = {
    "dev" = {
      project = data.google_project.dev.project_id
      bucket  = "music-collection-dev-tfstate"
    }
    "prod" = {
      project = data.google_project.prod.project_id
      bucket  = "music-collection-prod-tfstate"
    }
  }
}

# `force_destroy = false` és verziózás: az állapot elvesztése a topológia elvesztése.
resource "google_storage_bucket" "tfstate" {
  for_each                    = local.state_buckets
  name                        = each.value.bucket
  project                     = each.value.project
  location                    = var.region
  uniform_bucket_level_access = true
  force_destroy               = false

  versioning {
    enabled = true
  }
}

output "state_buckets" {
  value = { for k, b in google_storage_bucket.tfstate : k => b.name }
}
