# Generated by `zs workspace create` / `zs cloud`. Safe to edit & commit.
variable "project_id" { type = string }
variable "project_name" { type = string }
variable "billing_account" { type = string }
variable "org_id" {
  type    = string
  default = ""
}
variable "folder_id" {
  type    = string
  default = ""
}
variable "services" { type = list(string) }
variable "deletion_policy" {
  type    = string
  default = "DELETE"
}

resource "google_project" "this" {
  name            = var.project_name
  project_id      = var.project_id
  billing_account = var.billing_account
  org_id          = var.org_id != "" ? var.org_id : null
  folder_id       = var.folder_id != "" ? var.folder_id : null
  deletion_policy = var.deletion_policy
}

resource "google_project_service" "enabled" {
  for_each                   = toset(var.services)
  project                    = google_project.this.project_id
  service                    = each.value
  disable_on_destroy         = false
  disable_dependent_services = false
}

output "project_id" {
  value = google_project.this.project_id
}

output "project_number" {
  value = google_project.this.number
}
