# Generated by `zs workspace create` / `zs cloud`. Safe to edit & commit.
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 6.0"
    }
  }
}

variable "repository" { type = string }
variable "environment" { type = string }
variable "reviewer_users" {
  type    = list(string)
  default = []
}
variable "reviewer_team_ids" {
  type    = list(number)
  default = []
}
variable "wait_timer" {
  type    = number
  default = 0
}
variable "environment_variables" {
  type    = map(string)
  default = {}
}

resource "github_repository_environment" "this" {
  repository  = var.repository
  environment = var.environment
  wait_timer  = var.wait_timer

  dynamic "reviewers" {
    for_each = (length(var.reviewer_users) > 0 || length(var.reviewer_team_ids) > 0) ? [1] : []
    content {
      users = var.reviewer_users
      teams = var.reviewer_team_ids
    }
  }

  # Az ágak nem védettek, így a `protected_branches = true` minden telepítést blokkolna.
  # Helyette név szerinti szabály: csak a `deployment_branches` ágairól lehet telepíteni.
  deployment_branch_policy {
    protected_branches     = false
    custom_branch_policies = true
  }
}

variable "deployment_branches" {
  type    = list(string)
  default = ["main"]
}

resource "github_repository_environment_deployment_policy" "branches" {
  for_each       = toset(var.deployment_branches)
  repository     = var.repository
  environment    = github_repository_environment.this.environment
  branch_pattern = each.value
}

resource "github_actions_environment_variable" "this" {
  for_each      = var.environment_variables
  repository    = var.repository
  environment   = github_repository_environment.this.environment
  variable_name = each.key
  value         = each.value
}
